spring.application.name=SpringOAuth2

server.port=8000
spring.security.oauth2.client.registration.google.client-id=xyz
spring.security.oauth2.client.registration.google.client-secret=xyz

spring.security.oauth2.client.registration.github.client-id=xyz
spring.security.oauth2.client.registration.github.client-secret=xyz